-- MySQL Script generated by MySQL Workbench
-- Wed Jun  4 22:31:50 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Categoria` (
  `idCategoria` INT NOT NULL,
  `NombreCategoria` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`idCategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Empresa` (
  `idEmpresa` INT NOT NULL,
  `NombreEmpresa` VARCHAR(45) NULL,
  `rasonSocial` VARCHAR(45) NULL,
  `Ruc` VARCHAR(45) NULL,
  `Ubicacion` VARCHAR(45) NULL,
  `Msion` VARCHAR(45) NULL,
  `Vision` VARCHAR(45) NULL,
  PRIMARY KEY (`idEmpresa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Sucursal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Sucursal` (
  `idSucursal` INT NOT NULL,
  `nombreSucursal` VARCHAR(45) NULL,
  `Ubicacion` VARCHAR(45) NULL,
  `Empresa_idEmpresa` INT NOT NULL,
  `telefono` VARCHAR(45) NULL,
  `Whatsapp` VARCHAR(9) NULL,
  PRIMARY KEY (`idSucursal`),
  INDEX `fk_Sucursal_Empresa1_idx` (`Empresa_idEmpresa` ASC) VISIBLE,
  CONSTRAINT `fk_Sucursal_Empresa1`
    FOREIGN KEY (`Empresa_idEmpresa`)
    REFERENCES `mydb`.`Empresa` (`idEmpresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Producto` (
  `idProducto` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  `fechaVencimiento` VARCHAR(45) NULL,
  `precioUnitario` VARCHAR(45) NULL,
  `Categoria_idCategoria` INT NOT NULL,
  `Stock` VARCHAR(45) NULL,
  `Codigo` VARCHAR(45) NULL,
  `Estado` VARCHAR(45) NULL,
  `Sucursal_idSucursal` INT NOT NULL,
  PRIMARY KEY (`idProducto`),
  INDEX `fk_Producto_Categoria_idx` (`Categoria_idCategoria` ASC) VISIBLE,
  INDEX `fk_Producto_Sucursal1_idx` (`Sucursal_idSucursal` ASC) VISIBLE,
  CONSTRAINT `fk_Producto_Categoria`
    FOREIGN KEY (`Categoria_idCategoria`)
    REFERENCES `mydb`.`Categoria` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Producto_Sucursal1`
    FOREIGN KEY (`Sucursal_idSucursal`)
    REFERENCES `mydb`.`Sucursal` (`idSucursal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cargo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cargo` (
  `idCargo` INT NOT NULL,
  `nombreCargo` VARCHAR(45) NULL,
  PRIMARY KEY (`idCargo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Trabajador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Trabajador` (
  `idTrabajador` INT NOT NULL,
  `nombres` VARCHAR(45) NULL,
  `apellidoPaterno` VARCHAR(45) NULL,
  `apellidoMaterno` VARCHAR(45) NULL,
  `DNI` VARCHAR(45) NULL,
  `CELUALR` VARCHAR(45) NULL,
  `EMAIL` VARCHAR(45) NULL,
  `FechaNacimiento` VARCHAR(45) NULL,
  `Cargo_idCargo` INT NOT NULL,
  `Sucursal_idSucursal` INT NOT NULL,
  PRIMARY KEY (`idTrabajador`),
  INDEX `fk_Trabajador_Cargo1_idx` (`Cargo_idCargo` ASC) VISIBLE,
  INDEX `fk_Trabajador_Sucursal1_idx` (`Sucursal_idSucursal` ASC) VISIBLE,
  CONSTRAINT `fk_Trabajador_Cargo1`
    FOREIGN KEY (`Cargo_idCargo`)
    REFERENCES `mydb`.`Cargo` (`idCargo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Trabajador_Sucursal1`
    FOREIGN KEY (`Sucursal_idSucursal`)
    REFERENCES `mydb`.`Sucursal` (`idSucursal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MedioDePago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`MedioDePago` (
  `idMedioDePago` INT NOT NULL,
  `nombreMedioPago` VARCHAR(45) NULL,
  `Descripcion` VARCHAR(45) NULL,
  `DatosDepago` VARCHAR(45) NULL,
  PRIMARY KEY (`idMedioDePago`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `idCliente` INT NOT NULL,
  `Nombres` VARCHAR(45) NULL,
  `ApellidoPaterno` VARCHAR(45) NULL,
  `ApellidoMaterno` VARCHAR(45) NULL,
  `DNI` VARCHAR(45) NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Venta` (
  `idVenta` INT NOT NULL,
  `FechaVenta` VARCHAR(45) NULL,
  `precioTotal` VARCHAR(45) NULL,
  `Igv` VARCHAR(45) NULL,
  `CodigoVenta` VARCHAR(20) NULL,
  `Trabajador_idTrabajador` INT NOT NULL,
  `MedioDePago_idMedioDePago` INT NOT NULL,
  `Cliente_idCliente` INT NOT NULL,
  `Vuelto` VARCHAR(45) NULL,
  `MontoEntregado` VARCHAR(45) NULL,
  PRIMARY KEY (`idVenta`),
  INDEX `fk_Venta_Trabajador1_idx` (`Trabajador_idTrabajador` ASC) VISIBLE,
  INDEX `fk_Venta_MedioDePago1_idx` (`MedioDePago_idMedioDePago` ASC) VISIBLE,
  INDEX `fk_Venta_Cliente1_idx` (`Cliente_idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_Venta_Trabajador1`
    FOREIGN KEY (`Trabajador_idTrabajador`)
    REFERENCES `mydb`.`Trabajador` (`idTrabajador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Venta_MedioDePago1`
    FOREIGN KEY (`MedioDePago_idMedioDePago`)
    REFERENCES `mydb`.`MedioDePago` (`idMedioDePago`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Venta_Cliente1`
    FOREIGN KEY (`Cliente_idCliente`)
    REFERENCES `mydb`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`VentaDetalle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`VentaDetalle` (
  `Venta_idVenta` INT NOT NULL,
  `Producto_idProducto` INT NOT NULL,
  `precioUnitario` VARCHAR(45) NULL,
  `cantidad` VARCHAR(45) NULL,
  `idVentaDetalle` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Venta_idVenta`, `Producto_idProducto`, `idVentaDetalle`),
  INDEX `fk_Venta_has_Producto_Producto1_idx` (`Producto_idProducto` ASC) VISIBLE,
  INDEX `fk_Venta_has_Producto_Venta1_idx` (`Venta_idVenta` ASC) VISIBLE,
  CONSTRAINT `fk_Venta_has_Producto_Venta1`
    FOREIGN KEY (`Venta_idVenta`)
    REFERENCES `mydb`.`Venta` (`idVenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Venta_has_Producto_Producto1`
    FOREIGN KEY (`Producto_idProducto`)
    REFERENCES `mydb`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Compra` (
  `idCompra` INT NOT NULL,
  `FechaCompra` VARCHAR(45) NULL,
  `PrecioTotal` VARCHAR(45) NULL,
  `igv` VARCHAR(45) NULL,
  `codigo` VARCHAR(45) NULL,
  `Trabajador_idTrabajador` INT NOT NULL,
  `MedioDePago_idMedioDePago` INT NOT NULL,
  PRIMARY KEY (`idCompra`),
  INDEX `fk_Compra_Trabajador1_idx` (`Trabajador_idTrabajador` ASC) VISIBLE,
  INDEX `fk_Compra_MedioDePago1_idx` (`MedioDePago_idMedioDePago` ASC) VISIBLE,
  CONSTRAINT `fk_Compra_Trabajador1`
    FOREIGN KEY (`Trabajador_idTrabajador`)
    REFERENCES `mydb`.`Trabajador` (`idTrabajador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Compra_MedioDePago1`
    FOREIGN KEY (`MedioDePago_idMedioDePago`)
    REFERENCES `mydb`.`MedioDePago` (`idMedioDePago`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CompraDetalle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CompraDetalle` (
  `Compra_idCompra` INT NOT NULL,
  `Producto_idProducto` INT NOT NULL,
  `PrecioUnitario` VARCHAR(45) NULL,
  `Cantidad` VARCHAR(45) NULL,
  `idCompraDetalle` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Compra_idCompra`, `Producto_idProducto`, `idCompraDetalle`),
  INDEX `fk_Compra_has_Producto_Producto1_idx` (`Producto_idProducto` ASC) VISIBLE,
  INDEX `fk_Compra_has_Producto_Compra1_idx` (`Compra_idCompra` ASC) VISIBLE,
  CONSTRAINT `fk_Compra_has_Producto_Compra1`
    FOREIGN KEY (`Compra_idCompra`)
    REFERENCES `mydb`.`Compra` (`idCompra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Compra_has_Producto_Producto1`
    FOREIGN KEY (`Producto_idProducto`)
    REFERENCES `mydb`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
